### ISSUE TITLE
Current version links out to Ethereum mainnet beacon explorer, should be Pulsechain explorer.

### ISSUE THREAD

**Issue by JexxaJ** [raskitoma/pulse-staking-dashboard#2]
changing the current references of 

"targetBlank": true,
"title": "https://beaconcha.in/validator/${__value.raw}",
"url": "https://beaconcha.in/validator/${__value.raw}"

to be 

"targetBlank": true,
"title": "https://beacon.v4.testnet.pulsechain.com/validator/${__value.raw}",
"url": "https://beacon.v4.testnet.pulsechain.com/validator/${__value.raw}"

Will forward links to the current Pulsechain testnet v4 beacon explorer

[Jexxa_Yoldark_PLS_staking_dashboard.json.txt](https://github.com/raskitoma/pulse-staking-dashboard/files/11328133/Jexxa_Yoldark_PLS_staking_dashboard.json.txt)

**Comment by JexxaJ** [comment]
Even better solution is to add an input for this as well so the users can set the URL at time of import

    {
      "name": "BEACON_EXPLORER",
      "type": "constant",
      "label": "Explorer_Url",
      "value": "https://beacon.v4.testnet.pulsechain.com/",
      "description": ""
    }




             {
                "id": "links",
                "value": [
                  {
                    "targetBlank": true,
                    "title": "${BEACON_EXPLORER}/validator/${__value.raw}",
                    "url": "${BEACON_EXPLORER}/validator/${__value.raw}"
                  }
[Explorer_Jexxa_Yoldark_PLS_staking_dashboard.json.txt](https://github.com/raskitoma/pulse-staking-dashboard/files/11330984/Explorer_Jexxa_Yoldark_PLS_staking_dashboard.json.txt)

**Comment by raskitoma** [comment]
Fixed [2e0a6a0](https://github.com/raskitoma/pulse-staking-dashboard/commit/2e0a6a0aebdf15e7a2319f2a8d88bdac54110ec0)
